### ISSUE TITLE
Some struct error when opening wupclient.py

### ISSUE THREAD

**Issue by gary435676** [smealum/iosuhax#5]
Hi, I'm trying to use wupclient.py to change the file permissions of slccmpt01 (vWii). However, I keep getting a struct error when trying to open wupclient.py:

C:\Python27>python.exe -i wupclient.py
svc error : 32323020
Traceback (most recent call last):
  File "wupclient.py", line 911, in <module>
    mount_sd()
  File "wupclient.py", line 679, in mount_sd
    handle = w.open("/dev/fsa", 0)
  File "wupclient.py", line 142, in open
    address = self.load_string(device)
  File "wupclient.py", line 139, in load_string
    return self.load_buffer(bytearray(s + "\0", "ascii"), align)
  File "wupclient.py", line 135, in load_buffer
    self.write(address, b)
  File "wupclient.py", line 70, in write
    data = struct.pack(">I", addr) + data
struct.error: cannot convert argument to integer
>>>

I'm using Python 2.7.9 (64-bit) for Windows. Is there any solution to this problem? Thanks.

**Comment by KP2048** [comment]
i got this error too
